#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LiteID.Resource", IsApplication=true)]

namespace LiteID
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_grad_256 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_grad_d_256 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_add = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_add_192 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_add_p_192 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_options = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_options_192 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_options_p_192 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int group_border = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon4sc_256 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo_inv_256 = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001e
			public const int buttonAdd = 2131165214;
			
			// aapt resource value: 0x7f070011
			public const int buttonCreate = 2131165201;
			
			// aapt resource value: 0x7f07001b
			public const int buttonDelete = 2131165211;
			
			// aapt resource value: 0x7f070012
			public const int buttonDiscard = 2131165202;
			
			// aapt resource value: 0x7f07001a
			public const int buttonExport = 2131165210;
			
			// aapt resource value: 0x7f07000b
			public const int buttonFile = 2131165195;
			
			// aapt resource value: 0x7f070020
			public const int buttonGenerateAccount = 2131165216;
			
			// aapt resource value: 0x7f070017
			public const int buttonOpen = 2131165207;
			
			// aapt resource value: 0x7f07001c
			public const int buttonOptions = 2131165212;
			
			// aapt resource value: 0x7f070021
			public const int buttonResetID = 2131165217;
			
			// aapt resource value: 0x7f070024
			public const int buttonSaveRPC = 2131165220;
			
			// aapt resource value: 0x7f070019
			public const int docContent = 2131165209;
			
			// aapt resource value: 0x7f070014
			public const int docDate = 2131165204;
			
			// aapt resource value: 0x7f07001f
			public const int docList = 2131165215;
			
			// aapt resource value: 0x7f070013
			public const int docTitle = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int docType = 2131165206;
			
			// aapt resource value: 0x7f07001d
			public const int imageView1 = 2131165213;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout2 = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout3 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout4 = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout5 = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout6 = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int modeFile = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int modeText = 2131165208;
			
			// aapt resource value: 0x7f07000a
			public const int radioFile = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int radioGroup1 = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int radioText = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int textContent = 2131165199;
			
			// aapt resource value: 0x7f070022
			public const int textCurrentID = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int textRPCAddress = 2131165219;
			
			// aapt resource value: 0x7f070004
			public const int textTitle = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int textView2 = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int textView3 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int textView4 = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int textView5 = 2131165196;
			
			// aapt resource value: 0x7f070025
			public const int textView6 = 2131165221;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddDoc = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DocView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Options = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int LiteID_Main = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
